---
# tasks file for hello
- name: Printing a new line 
  debug:
          msg: "Hello beautiful people me"

- name: using the command
  command: "ifconfig"
  register: cmd

- name: debuging the command
  debug:
          var: cmd
